spring:
# DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.138.215:3306/usercenter
    username: root
    password: Saji@1987
  # session ????
  session:
    timeout: 86400


